wip

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -789,14 +789,22 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
+HAVE_DOT_FALSE
+HAVE_DOT_TRUE
 DOT
+HAVE_DOXYGEN_FALSE
+HAVE_DOXYGEN_TRUE
 DOXYGEN
+HAVE_PDFLATEX_FALSE
+HAVE_PDFLATEX_TRUE
 PDFLATEX
 ENABLE_DISASSEMBLY_FALSE
 ENABLE_DISASSEMBLY_TRUE
 PYTHON_LIBS
 PYTHON_CFLAGS
 PKG_CONFIG
+HAVE_PYTHON_FALSE
+HAVE_PYTHON_TRUE
 pkgpyexecdir
 pyexecdir
 pkgpythondir
@@ -4453,13 +4461,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4456: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4464: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4459: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4467: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4462: output\"" >&5)
+  (eval echo "\"\$as_me:4470: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5665,7 +5673,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5668 "configure"' > conftest.$ac_ext
+  echo '#line 5676 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7492,11 +7500,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7495: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7503: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7499: \$? = $ac_status" >&5
+   echo "$as_me:7507: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7831,11 +7839,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7834: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7842: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7838: \$? = $ac_status" >&5
+   echo "$as_me:7846: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7936,11 +7944,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7939: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7947: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7943: \$? = $ac_status" >&5
+   echo "$as_me:7951: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7991,11 +7999,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7994: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8002: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7998: \$? = $ac_status" >&5
+   echo "$as_me:8006: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10794,7 +10802,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10797 "configure"
+#line 10805 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10890,7 +10898,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10893 "configure"
+#line 10901 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11305,9 +11313,19 @@ $as_echo "$am_cv_python_pyexecdir" >&6; }
   fi
 
 
+ if test -n "$PYTHON"; then
+  HAVE_PYTHON_TRUE=
+  HAVE_PYTHON_FALSE='#'
+else
+  HAVE_PYTHON_TRUE='#'
+  HAVE_PYTHON_FALSE=
+fi
+
 if test -z "$PYTHON"; then
-    echo "Essential program python not found"
-    exit 1
+    echo "The python interpreter was not found in the search path. The Python language bindings"
+    echo "will not be built.  If you want to build the Python language bindings, please ensure"
+    echo "that python is installed and its directory is included in the search path."
+    echo "Then run configure again before attempting to build Btparser."
 fi
 
 # Just PKG_CHECK_MODULES([PYTHON], [python]) works only with python2.7+
@@ -11598,11 +11616,19 @@ $as_echo "no" >&6; }
 fi
 
 
+ if test "$PDFLATEX" != "no"; then
+  HAVE_PDFLATEX_TRUE=
+  HAVE_PDFLATEX_FALSE='#'
+else
+  HAVE_PDFLATEX_TRUE='#'
+  HAVE_PDFLATEX_FALSE=
+fi
+
 if test "$PDFLATEX" = "no"; then
-    echo "The pdflatex program was not found in the search path. Please ensure"
-    echo "that it is installed and its directory is included in the search path."
-    echo "Then run configure again before attempting to build Canal."
-    exit 1
+    echo "The pdflatex program was not found in the search path. The documentation"
+    echo "will not be built.  If you want to build the documentation, please ensure"
+    echo "that pdflatex is installed and its directory is included in the search path."
+    echo "Then run configure again before attempting to build Btparser."
 fi
 
 # doxygen
@@ -11647,10 +11673,19 @@ $as_echo "no" >&6; }
 fi
 
 
+ if test "$DOXYGEN" != "no"; then
+  HAVE_DOXYGEN_TRUE=
+  HAVE_DOXYGEN_FALSE='#'
+else
+  HAVE_DOXYGEN_TRUE='#'
+  HAVE_DOXYGEN_FALSE=
+fi
+
 if test "$DOXYGEN" = "no"; then
-    echo "The doxygen program was not found in the search path. Please ensure"
-    echo "that it is installed and its directory is included in the search path."
-    echo "Then run configure again before attempting to build Canal."
+    echo "The doxygen program was not found in the search path. The documentation"
+    echo "will not be built.  If you want to build the documentation, please ensure"
+    echo "that doxygen is installed and its directory is included in the search path."
+    echo "Then run configure again before attempting to build Btparser."
     exit 1
 fi
 
@@ -11696,11 +11731,19 @@ $as_echo "no" >&6; }
 fi
 
 
+ if test "$DOT" != "no"; then
+  HAVE_DOT_TRUE=
+  HAVE_DOT_FALSE='#'
+else
+  HAVE_DOT_TRUE='#'
+  HAVE_DOT_FALSE=
+fi
+
 if test "DOT" = "no"; then
-    echo "The dot program was not found in the search path. Please ensure"
-    echo "that it is installed and its directory is included in the search path."
-    echo "Then run configure again before attempting to build Canal."
-    exit 1
+    echo "The dot program was not found in the search path. The documentation"
+    echo "will not be built.  If you want to build the documentation, please ensure"
+    echo "that dot is installed and its directory is included in the search path."
+    echo "Then run configure again before attempting to build Btparser."
 fi
 
 ac_config_files="$ac_config_files btparser.spec btparser.pc Makefile lib/Makefile python/Makefile docs/Makefile tests/Makefile tests/atlocal"
@@ -11868,10 +11911,38 @@ $as_echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_PYTHON_TRUE}" && test -z "${HAVE_PYTHON_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"HAVE_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"HAVE_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${ENABLE_DISASSEMBLY_TRUE}" && test -z "${ENABLE_DISASSEMBLY_FALSE}"; then
   { { $as_echo "$as_me:$LINENO: error: conditional \"ENABLE_DISASSEMBLY\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 $as_echo "$as_me: error: conditional \"ENABLE_DISASSEMBLY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_PDFLATEX_TRUE}" && test -z "${HAVE_PDFLATEX_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"HAVE_PDFLATEX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"HAVE_PDFLATEX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_DOXYGEN_TRUE}" && test -z "${HAVE_DOXYGEN_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"HAVE_DOXYGEN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"HAVE_DOXYGEN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_DOT_TRUE}" && test -z "${HAVE_DOT_FALSE}"; then
+  { { $as_echo "$as_me:$LINENO: error: conditional \"HAVE_DOT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+$as_echo "$as_me: error: conditional \"HAVE_DOT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
